import type { Metadata } from "next";
import { Inter } from "next/font/google";
import '@/styles/globals.css'
import Navbar from "@/components/Navbar";
import Sidebar from "@/components/Sidebar";

const inter = Inter({ subsets: ["latin"], weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"] });


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
          <Navbar />
          <Sidebar 
            userName="Sundar Gurung"
            userEmail="sundargurung360@gmail.com"
          />
          <main className="ml-[240px] mt-[89px] overflow-visible">
            {children}
          </main>
      </body>
    </html>
  );
}
